name: 🐞 Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: bug-report
    attributes:
      label: Bug Report
      description: Please describe the bug in detail
      value: |
        ## 🐞 Bug Report

        ### Description
        [A clear and concise description of what the bug is]

        ### Steps to Reproduce
        1. [First Step]
        2. [Second Step]
        3. [and so on...]

        ### Expected Behavior
        [What you expected to happen]

        ### Actual Behavior
        [What actually happened]

        ### Environment
        - Browser: [e.g. Chrome, Safari]
        - OS: [e.g. Windows, MacOS]
        - Version: [e.g. v1.0.0]

        ### Additional Context
        [Add any other context, screenshots, or error messages about the problem here]
    validations:
      required: true
