blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/yansircc/payload-builder/wiki
    about: Check our documentation first
  - name: 💬 Discussions
    url: https://github.com/yansircc/payload-builder/discussions
    about: Please ask and answer questions here