name: 🚀 Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['FR']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: feature-proposal
    attributes:
      label: Feature Proposal
      description: Please describe your feature request in detail
      value: |
        ## 🚀 Feature Request

        ### Description
        [Describe the feature you'd like to see added. Be specific about what it does and how it should work]

        ### Motivation
        [Why is this feature needed? What problems does it solve?]

        ### Use Case
        [Provide specific examples of how this feature would be used]

        ### Proposed Solution
        [How do you think this could be implemented?]

        ### Alternatives Considered
        [What alternatives have you considered?]

        ### Tasks
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3

        ### Additional Context
        [Any other context, screenshots, or examples?]
    validations:
      required: true

  - type: dropdown
    id: contribute
    attributes:
      label: Would you like to work on this feature?
      options:
        - 'Yes'
        - 'No'
        - 'Maybe (I need guidance)'
